# Generated by Django 5.1.1 on 2024-09-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nodes',
            field=models.ManyToManyField(blank=True, related_name='persons', to='nodes.node'),
        ),
    ]
