# Generated by Django 5.1.1 on 2024-09-12 01:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_person_nodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
